version: 0.1.{build}
branches:
  only:
  - feature/unity_package
configuration: Release
environment:
  nodejs_version: STABLE
  NPM_TOKEN:
    secure: eBrnjT3GvCjDXqBN/Q4g7hMIchMToOerQeoZrG/OC8QGBVVV7S4Kq+SSv4xTWQe+  
install:
- ps: Install-Product node $env:nodejs_version
build: off
artifacts:
- path: '**\*.tgz'
deploy_script:
- ps: >-
    $packagesFiles = Get-ChildItem -Path $env:APPVEYOR_BUILD_FOLDER -Include "package.json" -Recurse
    
    foreach ($package in $packagesFiles)
    {
        Set-Location -Path $package.Directory.FullName
        "//npm.pkg.github.com/:_authToken={0}" -f $env:NPM_TOKEN | Out-File ".npmrc" -Encoding UTF8
        
        Invoke-Expression -Command "npm publish"
    }