version: 0.1.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore NetworkOperation.sln
build:
  project: NetworkOperation.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: oAm98i6tHeFejTwW4uzx1+LeqshooAI+WEHJ/ux8Nx0voxB/fuw5cbcOZZBy0wvb
  skip_symbols: true
  artifact: /.*\.nupkg/