version: 0.3.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore NetworkOperation.sln
build:
  project: NetworkOperation.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 6Ssbwk10OU2U08WMOW2Cn0oyHOa3n++bg5zctQWnHcwmaRkNr8QvZPqaOqBSvSRP
  skip_symbols: true
  symbol_server:
  artifact: /.*\.nupkg/