// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateDispatcher
{
    using NetworkOperation.Core;
    using NetworkOperation.Core.Models;
    using TemplateDispatcher;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class PreGeneratedDispatcherTemplate : PreGeneratedDispatcherTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Threading.Tasks;\r\nusing System.Threading;\r\nusing NetworkOperation.Core;\r\nusing NetworkOperation.Core.Dispatching;\r\nusing NetworkOperation.Core.Models;\r\nusing NetworkOperation.Core.Messages;\r\nusing Microsoft.Extensions.Logging;\r\n\r\n\r\nnamespace NetworkOperations.Dispatching\r\n{\r\n    public class PreGeneratedDispatcher<TRequest, TResponse> : BaseDispatcher<TRequest, TResponse>\r\n           where TRequest : IOperationMessage, new() where TResponse : IOperationMessage, new()\r\n    {\r\n        public PreGeneratedDispatcher(BaseSerializer serializer, IHandlerFactory factory, OperationRuntimeModel model, ILoggerFactory logger, DescriptionRuntimeModel descriptionRuntimeModel) : base(serializer, factory, model, logger,descriptionRuntimeModel)\r\n        {\r\n        }\r\n\r\n        protected override Task<DataWithStateCode> ProcessHandler(TRequest message, RequestContext<TRequest> context, CancellationToken token)\r\n        {\r\n            switch (context.OperationDescription.Code)\r\n            {\r\n");
            
            #line 37 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
 foreach (OperationDescription op in Model) { if (op == null || !op.Handle.HasFlag(Side)) continue; 
            
            #line default
            #line hidden
            this.Write("               case ");
            
            #line 38 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Code));
            
            #line default
            #line hidden
            this.Write(": return GenericHandle<");
            
            #line 38 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.OperationType.FullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 38 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.ResultType.ToCSharpFormat()));
            
            #line default
            #line hidden
            this.Write(">(message, context, token);\r\n");
            
            #line 39 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n            throw new InvalidOperationException($\"Wrong code operation {context.OperationDescription.Code}\");\r\n        }\r\n    }\r\n    \r\n");
            
            #line 45 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
 if (AOTSupport) {
            
            #line default
            #line hidden
            this.Write(" \r\n        public static partial class AOTSupport\r\n        {\r\n            public static void GeneratedDefinitions()\r\n            {\r\n");
            
            #line 50 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
 foreach (OperationDescription op in Model){
            
            #line default
            #line hidden
            this.Write("                VirtualGenericMethodsDefinition<");
            
            #line 51 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.OperationType.FullName));
            
            #line default
            #line hidden
            this.Write(">();                                        \r\n");
            
            #line 52 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("            \r\n");
            
            #line 54 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
 foreach (Type resultType in Model.Select(d => d.ResultType).Distinct()){
            
            #line default
            #line hidden
            this.Write("                VirtualGenericMethodsDefinition<");
            
            #line 55 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resultType.ToCSharpFormat()));
            
            #line default
            #line hidden
            this.Write(">();                                       \r\n");
            
            #line 56 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("            }            \r\n            static partial void VirtualGenericMethodsDefinition<T>();            \r\n        }\r\n");
            
            #line 60 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\projects\NetworkOperation\AutoDispatchers\PreGeneratedDispatcherTemplate.tt"

private bool _AOTSupportField;

/// <summary>
/// Access the AOTSupport parameter of the template.
/// </summary>
private bool AOTSupport
{
    get
    {
        return this._AOTSupportField;
    }
}

private global::NetworkOperation.Core.Side _SideField;

/// <summary>
/// Access the Side parameter of the template.
/// </summary>
private global::NetworkOperation.Core.Side Side
{
    get
    {
        return this._SideField;
    }
}

private global::NetworkOperation.Core.Models.OperationRuntimeModel _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::NetworkOperation.Core.Models.OperationRuntimeModel Model
{
    get
    {
        return this._ModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool AOTSupportValueAcquired = false;
if (this.Session.ContainsKey("AOTSupport"))
{
    this._AOTSupportField = ((bool)(this.Session["AOTSupport"]));
    AOTSupportValueAcquired = true;
}
if ((AOTSupportValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AOTSupport");
    if ((data != null))
    {
        this._AOTSupportField = ((bool)(data));
    }
}
bool SideValueAcquired = false;
if (this.Session.ContainsKey("Side"))
{
    this._SideField = ((global::NetworkOperation.Core.Side)(this.Session["Side"]));
    SideValueAcquired = true;
}
if ((SideValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Side");
    if ((data != null))
    {
        this._SideField = ((global::NetworkOperation.Core.Side)(data));
    }
}
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::NetworkOperation.Core.Models.OperationRuntimeModel)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::NetworkOperation.Core.Models.OperationRuntimeModel)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class PreGeneratedDispatcherTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
